// <auto-generated />
namespace TaskManagerCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class v2_updatingChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2_updatingChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202010291301281_v2_updatingChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
